// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bokkopbcgisyalbrhtkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJva2tvcGJjZ2lzeWFsYnJodGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mjk5MzcsImV4cCI6MjA2NDUwNTkzN30.zfqkTNAhFEQiH2Iym_KT1TNSFmulZtNLFg1Q8qLW3e8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);